Fix bugs.

diff --git a/bin/fvid b/bin/fvid
--- a/bin/fvid
+++ b/bin/fvid
@@ -142,23 +142,46 @@ function say() {
   echo -e "${NC}$1"
 }
 
+function print_msg_for_error_code() {
+  [ "$1" -eq 1 ] && echo -e "found no match for '$search_text', abort" && return
+  [ "$1" -eq 2 ] && echo -e "found multiple possibilities for '$search_text', abort\n$result" && return
+}
+
+function find_one_file() {
+  [ -z "$1" ] || [ -z "$2" ] && echo "usage: find_one <TYPE_FILE_OR_DIR> <PARTIAL_NAME> [<DIRECTORY>]" && return
+  if [ -n "$3" ]; then search_dir="$3"; else search_dir="$wt_projects_dir"; fi
+  search_text="$2"
+  type="$1"
+
+  [ -f "$search_text" ] && echo "$search_text" && return
+  result=$(find "$search_dir" -type "$type" -iwholename "*$search_text*")
+  unset search_text
+
+  [ "$(wc -w <<<"$result")" -eq 0 ] && return 1
+  [ "$(wc -l <<<"$result")" -gt 1 ] && return 2
+  [ "$(wc -l <<<"$result")" -eq 1 ] && echo -e "$result"
+}
+
 function find_one_vmeta() {
+  [ -z "$1" ] && echo "usage: find_one_vmeta <VIDEO_SEARCH_TEXT> [<PLATFORM>]" && return
   search_text="$1"
   platform="$2"
 
-  # $meta_file determination.
-  if [ -f "$search_text" ]; then
-    meta_file="$search_text"
-  else
-    # $meta_file search.
-    results=$(find "$meta_dir" -type f -iwholename "*$platform*$search_text*metadata.json")
-    [ -z "$results" ] && return 1
-    count="$(wc -l <<<"$results")"
-    [ "$count" -eq 1 ] && meta_file="$results" || return 2
-  fi
+  [ -f "$search_text" ] && echo "$search_text" && return
+  result=$(find_one_file f "*$platform*$search_text*metadata.json" "$vids_meta_dir")
+  error=$? && if [ "$code" = 1 ]; then return 1; elif [ "$code" = 2 ]; then return 2; fi
+  echo "$result"
+}
 
-  [ -f "$meta_file" ] && title=$(basename "$meta_file" .json)
-  [ -n "$meta_file" ] && echo "$meta_file"
+function find_one_cmeta() {
+  [ -z "$1" ] && echo "usage: find_one_cmeta <CHANNEL_SEARCH_TEXT> [<PLATFORM>]" && return
+  search_text="$1"
+  platform="$2"
+
+  [ -f "$search_text" ] && echo "$search_text" && return
+  result=$(find_one_file f "*$search_text*$platform*metadata.json" "$channels_meta_dir")
+  error=$? && if [ "$code" = 1 ]; then return 1; elif [ "$code" = 2 ]; then return 2; fi
+  echo "$result"
 }
 
 function fvidv() {
@@ -220,21 +243,17 @@ function fvid() {
 }
 
 function fvidcv() {
-  usage="usage: fvidcv <CHANNEL_SEARCH_TEXT> <SEARCH_TEXT> [<PLATFORM>]\n       fvidcv <ABS_PATH_CHANNEL_JSON> <SEARCH_TEXT>"
-  if [ -n "$1" ]; then channel_search_name="$1"; else echo "$usage" && return 0; fi
-  if [ -n "$2" ]; then text=$(echo "$2" | tr '[:upper:]' '[:lower:]'); else echo "$usage" && return 0; fi
+  [ -z "$1" ] || [ -z "$2" ] &&
+    echo "usage: fvidcv <CHANNEL_SEARCH_TEXT> <TITLE_SEARCH_TEXT> [<PLATFORM>]" &&
+    echo "       fvidcv <CHANNEL_JSON_ABS_PATH> <TITLE_SEARCH_TEXT>" && return
+  channel_search_text="$(echo "$1" | tr '[:upper:]' '[:lower:]')"
+  search_text="$(echo "$2" | tr '[:upper:]' '[:lower:]')"
   platform="$3"
 
-  if [ -f "$channel_search_name" ]; then
-    json_file="$channel_search_name"
-  else
-    json_files=$(json_files_for_channel_name "$channel_search_name" "$platform")
-    [ -z "$json_files" ] && echo no match found && return 0
-    [[ "$json_files" == *$'\n'* ]] && msg_multiple_channels_found "fvidc" && return 0
-    json_file="$json_files" && unset json_files # only one entry in json_files
-  fi
+  json_file=$(find_one_cmeta "$channel_search_text" "$platform")
+  [ ! $? = 0 ] && return
 
-  results_json=$(
+  result=$(
     jq --arg search_text "$search_text" '.entries[] |
               select(
                   ( if .title != null then select(.title | ascii_downcase | contains($search_text)) else empty end ) or
@@ -243,9 +262,21 @@ function fvidcv() {
   )
   echo "search done"
 
-  json=$(jq -s '{ entries: . }' <<<"$results_json")
+  json=$(jq -s '{ entries: . }' <<<"$result")
   [ "$(jq '.entries | length' <<<"$json")" -eq 0 ] && echo "found nothing" && return
   opinionated_print
+
+# Output:
+#   title: x
+#   url: y
+#   description: z
+#
+#  result="$(
+#    jq -r --arg search_text "$search_text" --arg GREEN "$GREEN" --arg WHITE "$WHITE" '
+#      [.entries[] | select(.title | ascii_downcase | contains($search_text))] | unique_by(.webpage_url)[]
+#      | "\ntitle: " + .title + "\nurl: " + .webpage_url + "\ndescription:\n" + .description' "$json_file"
+#  )"
+#  echo "${GREEN}${result}${NC}"
 }
 
 function fvidfc() {
@@ -395,16 +426,16 @@ function chani() { # channel info
   [ -z "$1" ] &&
     echo "usage: chani <CHANNEL_SEARCH_TEXT>" &&
     echo "       chani <ABS_FILE_PATH> [<PLATFORM>]" && return
+  search_text=$(echo "$1" | tr "'" '*')
+  platform="$2"
 
-  if [ -f "$1" ]; then
-    json_file="$1"
-    json=$(jq '.' "$1")
+  if [ -f "$search_text" ]; then
+    json_file="$search_text"
+    json=$(jq '.' "$search_text")
   else
-    json_files=$(json_files_for_channel_name "$1" "$2")
-    [ -z "$json_files" ] && echo no match found && return 0
-    [[ "$json_files" == *$'\n'* ]] && msg_multiple_channels_found "chani" && return 0
-    json_file="$json_files" && unset json_files # only one entry in json_files
-    json=$(jq '.' "$json_file")
+    result=$(find_one_cmeta "$search_text" "$platform")
+    error=$? && [ ! "$code" = 0 ] && print_msg_for_error_code "$code" && return
+    json=$(jq '.' "$result")
   fi
 
   print_channel_label
@@ -548,7 +579,7 @@ function wp_convert_fvid_merge() {
 
   pwd=$(pwd)
   mkdir -p "$wp_export_dir/merge/oneliners"
-  cd /home/freetalk/code/vidhop || return 1
+  cd "$HOME/Code/vidhop" || return 1
   python -m cli.vidhop --wp-convert --merge-exports
   cd "$pwd" || return 1
 
@@ -564,7 +595,7 @@ function wp_convert_fvid_oneliner_file() {
 
   pwd=$(pwd)
   mkdir -p "$wp_export_dir/merge/oneliners"
-  cd /home/freetalk/code/vidhop || return 1
+  cd "$HOME/Code/vidhop" || return 1
   python -m cli.vidhop --wp-convert --input-file "$input_file"
   cd "$pwd" || return 1
 }
diff --git a/bin/metadata b/bin/metadata
--- a/bin/metadata
+++ b/bin/metadata
@@ -28,26 +28,15 @@ function metadata_help() {
 }
 
 function metadata() {
+  # open metadata file of last download
+  [ -z "$1" ] && [ -f "$meta_file" ] && jq . "$meta_file" && return
+  [ -z "$1" ] && [ -f "$json_file" ] && jq . "$json_file" && return
   # arg is a path to json file
   [ -f "$1" ] && [[ "$1" == *.json ]] && jq . "$1" && return
   # arg is a search term
-  [ -n "$1" ] && found_meta_file="$(find_one_vmeta "$1")" && [ -f "$found_meta_file" ] && jq . "$found_meta_file" && return
-  # open metadata file of last download
-  [ -f "$meta_file" ] && jq . "$meta_file" && return
-  [ -f "$json_file" ] && jq . "$meta_file" && return
-  echo "no metadata file found"
-}
-
-function channel-video-with-title() {
-  [ -z "$1" ] || [ -z "$2" ] && echo "usage: channel-video-with-title <CHANNEL_JSON_ABS_PATH> <TITLE_SEARCH_TEXT>" && return
-  json_file="$1"
-  search_text="$(echo "$2" | tr '[:upper:]' '[:lower:]')"
-  result="$(
-    jq -r --arg search_text "$search_text" --arg GREEN "$GREEN" --arg WHITE "$WHITE"  '
-      [.entries[] | select(.title | ascii_downcase | contains($search_text))] | unique_by(.webpage_url)[]
-      | "\ntitle: " + .title + "\nurl: " + .webpage_url + "\ndescription:\n" + .description' "$json_file"
-  )"
-  echo "${GREEN}${result}${NC}"
+  found_meta_file="$(find_one_vmeta "$1")"
+  error=$? && [ ! "$error" = 0 ] && print_msg_for_error_code "$error" && return
+  jq . "$found_meta_file"
 }
 
 function filesize-channel-meta-files() {
