Fix bugs.

diff --git a/bin/fvid b/bin/fvid
--- a/bin/fvid
+++ b/bin/fvid
@@ -150,16 +150,14 @@ function print_msg_for_error_code() {
 function find_one() {
   [ -z "$1" ] || [ -z "$2" ] && echo "usage: find_one <TYPE_FILE_OR_DIR> <PARTIAL_NAME> [<DIRECTORY>]" && return
   if [ -n "$3" ]; then search_dir="$3"; else search_dir="$projects_dir"; fi
-  search_text="$2"
+  unset search_text && search_text="$2"
   type="$1"
 
   [ -f "$search_text" ] && echo "$search_text" && return
   result=$(find "$search_dir" -type "$type" -iwholename "*$search_text*")
-  unset search_text
-
+  echo -e "$result"
   [ "$(wc -w <<<"$result")" -eq 0 ] && return 1
   [ "$(wc -l <<<"$result")" -gt 1 ] && return 2
-  [ "$(wc -l <<<"$result")" -eq 1 ] && echo -e "$result"
 }
 
 function find_one_vmeta() {
@@ -169,8 +167,9 @@ function find_one_vmeta() {
 
   [ -f "$search_text" ] && echo "$search_text" && return
   result=$(find_one f "*$platform*$search_text*metadata.json" "$vids_meta_dir")
-  error=$? && if [ "$error" = 1 ]; then return 1; elif [ "$error" = 2 ]; then return 2; fi
+  error=$?
   echo "$result"
+  if [ "$error" = 1 ]; then return 1; elif [ "$error" = 2 ]; then return 2; fi
 }
 
 function find_one_cmeta() {
@@ -204,6 +203,7 @@ function fvidv() {
                 ( if .description != null then select(.description | ascii_downcase | contains($text)) else empty end )
             )' "$vidjson"
     )
+    [ ! $? = 0 ] && echo "jq could not parse '$vidjson'"
   done < <(find "$vids_meta_dir" -type f -iname "*.json")
 
   videos=$(jq -s '{ entries: . }' <<<"$videos")
@@ -227,6 +227,7 @@ function fvidc() {
                   ( if .description != null then select(.description | ascii_downcase | contains($text)) else empty end )
               )' "$chanjson"
     )
+    [ ! $? = 0 ] && echo "jq could not parse '$chanjson'"
   done < <(find "$channels_meta_dir" ! -name "avatar_data*json" -type f -iname "*json")
 
   channels=$(jq -s '{ entries: . }' <<<"$channels")
diff --git a/bin/metadata b/bin/metadata
--- a/bin/metadata
+++ b/bin/metadata
@@ -28,19 +28,19 @@ function metadata_help() {
 }
 
 function metadata() {
-  if [ -z "$1" ]; then
-    if [ -z "$json" ]; then
+  search_text="$1"
+  if [ -z "$search_text" ] &&  [ -z "$json" ]; then # no arg
       [ -f "$meta_file" ] && json="$(jq . "$meta_file")"
       [ -f "$json_file" ] && json="$(jq . "$json_file")"
-    fi
   fi
-  [ -f "$1" ] && [[ "$1" == *.json ]] && json="$(jq . "$1")"
+  [ -f "$search_text" ] && [[ "$search_text" == *.json ]] && json="$(jq . "$search_text")"  # file arg
   # arg is a search term
-  if [ -z "$json" ]; then
+  if [ -n "$search_text" ] && [ ! -f "$search_text" ]; then # search term arg
     unset error
-    found_meta_file="$(find_one_vmeta "$1")" && error=$?
-    [ "$error" = 0 ] && json="$(jq . "$found_meta_file")"
-    [ ! "$error" = 0 ] && print_msg_for_error_code "$error"
+    result="$(find_one_vmeta "$search_text")"
+    error=$?
+    [ "$error" = 0 ] && json="$(jq . "$result")"
+    [ ! "$error" = 0 ] && print_msg_for_error_code "$error" && return
   fi
   [ -z "$json" ] && echo "could not resolve a json file or variable to process, abort" && return
 
