Add: search for partial name in 'specs' function. Add search by partial name to 'linkvideo4project'. Remove empty dir when 0 search results for 'linkvideos4project' function. Remove function keyword from code base.

diff --git a/bin/project b/bin/project
--- a/bin/project
+++ b/bin/project
@@ -2,14 +2,14 @@
 # While reading the code, differentiate between "projects" in plural, which is the directory
 # that holds all individual projects which are referred to in singular as "project".
 
-function project_help() {
+project_help() {
   echo " Title: project"
   echo " Description: Create projects scaffolding and link VidHop video files."
   echo " Commands:"
   echo "    project <PROJECT_NAME> => Create new project with <PROJECT_NAME> in \$projects_dir."
   echo "    subproject <PROJECT_NAME> <SUBPROJECT_NAME>      => Create new subproject in <PROJECT_NAME> as <SUBPROJECT_NAME>."
   echo "    linkvid4project <VIDEO_FILE> <PROJECT_NAME>      => Creates a symbolic link of given <VIDEO_FILE> in project with name <PROJECT_NAME>."
-  echo "    link-videos4project <SEARCH_TEXT> <PROJECT_NAME> => Creates symbolic links in <PROJECT_NAME> for all video files found by fvidf <SEARCH_TEXT> (happens in the background)."
+  echo "    linkvideos4project <SEARCH_TEXT> <PROJECT_NAME> => Creates symbolic links in <PROJECT_NAME> for all video files found by fvidf <SEARCH_TEXT> (happens in the background)."
   echo "    fproj <SEARCH_TEXT>      => Find files whose name match <SEARCH_TEXT> in all projects."
   echo "    absfproj <SEARCH_TEXT>   => Identical to fproj but results are displayed as absolute paths."
   echo "    rmproject <PROJECT_NAME> => Remove the project with as name <PROJECT_NAME>."
@@ -82,24 +82,6 @@ mkimgdir4project() {
   ln -s "$(realpath "$projects_images_dir")/$project_name" "$projects_dir/$project_name/img"
 }
 
-# Create a symbolic link to video file (arg) in the videos directory of a project.
-# Example: linkvid4project "$shared/Movies/VidHop/videos/youtube.com/DNA self-assembly.mp4" "Nanotechnology"
-# Result: Symbolic link "$shared/Movies/Projects/Nanotechnology/DNA self-assembly.mp4"
-#         points to "$shared/Movies/VidHop/videos/youtube.com/DNA self-assembly.mp4".
-linkvid4project() {
-  [ -z "$1" ] && echo -e "usage: linkvid4project <VIDEO_FILE> <PROJECT_NAME>\nnote: <PROJECT_NAME> is case sensitive" && return
-  [ $# = 1 ] && file="$media_file" && project_name="$1"
-  [ $# = 2 ] && file="$(realpath "$1")" && project_name="$2"
-  [ ! -f "$file" ] && echo "$file is not a file" && return
-
-  project_dir="$projects_dir/$project_name"
-  [ ! -d "$project_dir" ] && echo "could not find directory $project_dir" && return
-
-  link_path="$project_dir/vid/$(basename "$file")"
-  ln -s "$file" "$link_path" || echo "failed to create link from '$file' to '$link_path'" && echo return
-  echo "created link from '$file' to '$link_path'"
-}
-
 # Command to create a new subproject e.g. Nanotechnology/Graphene.
 subproject() { # create a new project in dir /data/projects/wickedtruths.org
   [ -z "$1" ] || [ "$1" = "." ] || [ "$1" = ".." ] || [ "$1" = "/" ] && echo "usage subproject <PROJECT_NAME> <SUBPROJECT_NAME>" && return
@@ -140,16 +122,39 @@ mkimgdir4subproject() {
     "$(realpath "$projects_dir")/$project_name/$subproject_name/img"
 }
 
+# Create a symbolic link to video file (arg) in the videos directory of a project.
+# Example: linkvid4project "$shared/Movies/VidHop/videos/youtube.com/DNA self-assembly.mp4" "Nanotechnology"
+# Result: Symbolic link "$shared/Movies/Projects/Nanotechnology/DNA self-assembly.mp4"
+#         points to "$shared/Movies/VidHop/videos/youtube.com/DNA self-assembly.mp4".
+linkvid4project() {
+  [ -z "$1" ] && echo -e "usage: linkvid4project <VIDEO_FILE> <PROJECT_NAME>\nnote: <PROJECT_NAME> is case sensitive" && return
+  [ $# = 1 ] && file="$media_file" && project_name="$1"
+  [ $# = 2 ] && [ -f "$1" ] && file="$(realpath "$1")" && project_name="$2"
+  [ $# = 2 ] && [ ! -f "$1" ] && search_text="$1" && project_name="$2"
+
+  [ -n "$search_text" ] && file="$(find_one_video "$search_text")"
+  error=$?
+  [ "$error" = 1 ] && echo "found nothing" && return
+  [ "$error" = 2 ] && echo -e "found multiple:\n$result" && return
+
+  project_dir="$projects_dir/$project_name"
+  [ ! -d "$project_dir" ] && echo "could not find directory $project_dir" && return
+
+  link_path="$project_dir/vid/$(basename "$file")"
+  ln -s "$file" "$link_path" || echo "failed to create link from '$file' to '$link_path'" && echo return
+  echo "created link from '$file' to '$link_path'"
+  unset file search_text
+}
+
 # Creates symlinks from fvidf results in the project /vid directory, more precisely in,
 # <PROJECT_NAME/vid/Video File Links/<SEARCH_TEXT>.
-function link-videos4project() {
-  [ -z "$1" ] && echo "usage: link-videos4project <SEARCH_TEXT> <PROJECT_NAME>" &&
+linkvideos4project() {
+  [ -z "$1" ] && echo "usage: linkvideos4project <SEARCH_TEXT> <PROJECT_NAME>" &&
     echo " info: creates symbolic links in <PROJECT_NAME>/vid/<SEARCH_TEXT> for all search results that match <SEARCH_TEXT>" && return
   search_text="$1"
   project_dir="$projects_dir/$2"
   [ ! -d "$project_dir" ] && echo "project directory '$project_dir' does not exist, abort" && return
   dest_dir="$project_dir/vid/Video File Links/$search_text"
-  mkdir -p "$dest_dir"
 
   unset result
   found_something="false"
@@ -166,6 +171,7 @@ function link-videos4project() {
   echo "$result"
 
   echo "Creating links to video files in '$dest_dir'..."
+  mkdir -p "$dest_dir"
   cd "$dest_dir"
   list_md="$dest_dir/$search_text.md"
   list_txt="$dest_dir/$search_text.txt"
@@ -190,12 +196,18 @@ function link-videos4project() {
   echo "Done creating links to video files in '$dest_dir'."
 }
 
-function write_title_url_to_markdown_file() {
+fvidf4project() {
+  [ -z "$1" ] && echo "usage: fvidf4project <SEARCH_TEXT> <PROJECT_NAME>" &&
+    echo " info: creates symbolic links in <PROJECT_NAME>/vid/<SEARCH_TEXT> for all search results that match <SEARCH_TEXT>" && return
+  linkvideos4project "$@"
+}
+
+write_title_url_to_markdown_file() {
   line="$(jq '"- [" + .title + "](" + .webpage_url + ")"' "$metadata" | prefix_suffix_with_double_quotes)"
   echo "$line" >>"$list_md"
 }
 
-function write_title_url_to_txt_file() {
+write_title_url_to_txt_file() {
   title="$(jq '.title' "$metadata" | prefix_suffix_with_double_quotes)"
   webpage_url="$(jq '.webpage_url' "$metadata" | prefix_suffix_with_double_quotes)"
   echo -e "$title\n$webpage_url\n" >>"$list_txt"
